# base image
FROM ubuntu

# install ant, git, sass, minify, curl, yarn, unzip (not included in the base image).
RUN apt update -y &&\
    apt install -y --no-install-recommends ant git sass minify &&\
    apt install -y gnupg2 curl &&\
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - &&\
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt update -y &&\
    apt install -y yarn unzip
